### ISSUE TITLE
issue with Input::get('option')

### ISSUE THREAD

**Issue by ghost** [usm4n/PollingApp-AngularJS#1]
Hi
Thanks for your tutorial. it's so great

I have been following it. but I couldn't save my option to db. and I tried var_dump(Input::get('option')). but I got nothing. it's null value. 

Could you please help me?

Thanks in advance./.

**Comment by usm4n** [comment]
How are you posting the data? Is it a route parameter? `Input::get` only works for the query strings and the posted form data.

**Comment by ghost** [comment]
Hi,
Im using restangular instead of $http. and sent a payload request and used Request::input('option') instead of Input::get('option'). and it's working now. 

Thanks for your tutorial again

**Comment by usm4n** [comment]
You're welcome!

**Comment by usm4n** [comment]
BTW `Request::input` and `Input::get` are the same thing. ([ref](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Support/Facades/Input.php#L19))

Take Care :)

**Comment by ghost** [comment]
I think Input::get only get value from form data request type in this case type of request is payreload? do you think so?
